### ISSUE TITLE
Support for @std/esm .mjs

### ISSUE THREAD

**Issue by kmalakoff** [okgrow/merge-graphql-schemas#108]
I was wondering what you thought about supporting .jsm files through @std/esm. 

Basically, you would need to add this extension and if you with commonjs require look for a `default` on the imported symbol. It is a little more complicated if there is no default, but just asking...

**Comment by cfnelson** [comment]
@kmalakoff I haven't heard or come across the`.jsm` file extension before (I assume it stands for js module). I am aware of the`.mjs` extension which is currently behind the `--experimental-modules` flag since node 8.5.0. 

I am aware and have used `@std/esm` pkg and enjoy it a lot. I am a little confused and have to admit I do not understand what you are asking/requesting. Would you be able to clarify/explain further for me what you hope to achieve? We currently use `rollup` to build a `es` &  `cjs` bundle, are you unable to use the `es` bundle?

**Comment by kmalakoff** [comment]
Sorry, re-reading what I wrote wasn't clear...

The following doesn't work with .mjs files under the types folder:
```
import { fileLoader, mergeTypes } from 'merge-graphql-schemas';

const typesArray = fileLoader(path.join(__dirname, './types'));
```

I just ended up writing my own: https://github.com/kmalakoff/esm-require-directory

**Comment by cfnelson** [comment]
@kmalakoff We would be happy to have a PR for this if you are interested in submitting one. The specific code in question is [here](https://github.com/okgrow/merge-graphql-schemas/blob/master/src/file_loader.js#L59).

**Comment by kmalakoff** [comment]
@cfnelson thank you. I am not too sure of the intricacies of @std/esm, have a solution now, and am busy balancing work and a personal project so I think I'll need to pass. Sorry!

**Comment by RichardLitt** [comment]
@kmalakoff Thank you for being honest and letting us know! We'll be here if you have more free time, of course, so there's no pressure for us. :) Good luck and take care.
