### ISSUE TITLE
getting the error-- Specified query type "Query" not found in document.

### ISSUE THREAD

**Issue by anuragnagarkota** [okgrow/merge-graphql-schemas#119]
Hey

I have created a sample app using merge-graphql-schemas and build that using babel. But when I run the generated code(after build) I am getting the following error

 Specified query type "Query" not found in document.

Please help me out.

**Comment by RichardLitt** [comment]
Thanks @anuragnagarkota. Can you specify the version you're working with? Is there any chance you have the app available on GitHub in an open source repository?

**Comment by cfnelson** [comment]
@anuragnagarkota Not to sure if I understand your question exactly, but I can say that this package doesn't write any `GQL` to file. Also the pkg executes at runtime, e.g - isn't a babel plugin/or some build pre-processor and doesn't do anything during your app's build process.

Please see the [Readme's Usage section](https://github.com/okgrow/merge-graphql-schemas#usage) for how to correctly use this package in more details. Also the tests are a great way to understand the behaviour of this pkg in more detail.

If your having problems then it's likely due to your build setup & we would need to see an example repo to provide any meaningful assistance.

Hope this helps! 😃

**Comment by agatlin** [comment]
I have been getting the same error, and I understand what is happening. (Fortunately, there are a couple of simple fixes.)

If you compile (tsc) and have the .js files generated in the same directories as the .ts files, everything works as expected. 

However, if you are one of those folks who does not like to have your source directories cluttered with shit files and you specify a different output directory (e.g. using outDir under compiler options in tsconfig.json `"outDir": "./.dist"`), then the .graphql files are not, by default copied over to the output directory.

Solution 1:

To fix the problem, you could use something like gulp to handle the compiling and the copying of the asset files (the .graphql files) your output directory.

Solution 2:

Simply move your entire set of .graphql files outside of the structure where your .ts files are and allow your compiled files (the js files) to access them. In other words, you point to the proper directory from within your .ts files and have it still be valid for the compiled files.
