### ISSUE TITLE
Proposal: remove parent/root 1st argument from top-level queries and mutations

### ISSUE THREAD

**Issue by daviestar** [okgrow/merge-graphql-schemas#132]
Hey,

I've been using your package for a while and it's great - thanks!

Until now, I blindly accepted that the 1st argument to a resolver is always undefined, I assumed it was a 'nodeback' style `err, response` signature.

So I finally looked it up when a colleague asked about it (information is scarce on this!).  So now I realise it's the parent query, and hence makes sense in subqueries, but I can't think of a reason it'd ever not be undefined for top-level queries or mutations.

Here's some simple example code to illustrate my point:

_resolver.js_
```js
export default {
  Query: {
    async galleries(_, __, {userId}) {
      const galleries = await db.many(sql`
        select * from galleries
        where user_id = ${userId}
      `)
      return galleries
    },
    
    async gallery(_, {id}, {userId}) {
      const gallery = await db.one(sql`
        select * from galleries
        where user_id = ${userId}
        and id = ${id}
      `)
      return gallery
    }
  },
  
  Gallery: {
    async images({id}) {
      const images  = await db.many(sql`
        select *
        from images
        where gallery_id = ${id}
      `)
      return images
    },
  },

  Mutation: {
    async createGallery(_, {gallery}, {userId}) {
      const newGallery = await db.one(sql`
        insert into galleries ...
        returning *
      `)
      return newGallery
    },
}
```
_gallery.gql_
```js
type Gallery {
  id: Int
  title: String
  description: String
  images: [Image]
}

type Query {
  galleries: [Gallery]
  gallery(id: Int!): Gallery
}

input GalleryInput {
  title: String
  description: String
}

type Mutation {
  createGallery(gallery: GalleryInput!): Gallery
}
```

The query definition for `gallery()` indicate it's first argument will be `id` of type `Int`.

The mutation definition for `createGallery()` indicates it's first argument will be `gallery` of type `GalleryInput`.

Thanks.

**Comment by cfnelson** [comment]
@daviestar Can you explain a little more about what you are suggesting/proposing? Or is this more of a question/wishing for an example of how the `Root`/`Query` type can be useful? 

To be clear we don't define or control the[ GraphQL spec](https://facebook.github.io/graphql/October2016/) or its [reference JS](https://github.com/graphql/graphql-js) implementation. If you wish to read up more on the Root I would recommend reading [here](http://graphql.org/learn/execution/#root-fields-resolvers).

I will close this issue for now, but we will be happy to re-open if we have misunderstood this issue and the suggestion isn't that we introduce a change to this package that would conflict with the expected behaviour of GraphQL.
