### ISSUE TITLE
Directives must appear exactly once on a field

### ISSUE THREAD

**Issue by Fi1osof** [okgrow/merge-graphql-schemas#156]
Mayby bug.

Try to merge twice 
```
type User {
  id: ID! @unique
  fullname: String
}

type User {
  id: ID! @unique
  email: String
}
```

Got:
```
schema type User {
  id: ID! **@unique @unique**
  fullname: String
}
```
Error: The field `id` specifies a directive more than once. Directives must appear exactly once on a field.

**Comment by cfnelson** [comment]
Thanks for reporting this behaviour. 

The behaviour was introduced in PR https://github.com/okgrow/merge-graphql-schemas/pull/144 and it looks like we don't have a test for this.

The issue I believe will be due to this line https://github.com/okgrow/merge-graphql-schemas/pull/144/files#diff-3b4b88545526e76374a7547d901a272eR75 potentially the solution could be as simple as ensuring the directives are unique before concating them together.


This would likely be a good PR for anyone wishing to contribute to the project for the first time.

**Comment by ttapar** [comment]
Do you mind if I check this out?

**Comment by RichardLitt** [comment]
@ttapar Go ahead! Let us know if you need help.
