### ISSUE TITLE
Merge Named types

### ISSUE THREAD

**Issue by dyst5422** [okgrow/merge-graphql-schemas#24]
Seeing as there is a clear namespace conflict for having two similarly named types, I think there is no reason not to merge any named type.

```graphql
type MyType {
  name: String
}
```
and
```graphql
type MyType {
  age: Int
}
```
should become
```graphql
type MyType {
  name: String
  age: Int
}
```
but instead becomes
```graphql
type MyType {
  name: String
}
type MyType {
  age: Int
}
```

This is less of a concern for these types where you can just use extend, but input types cannot be extended, which makes this string parsing the only way to extend inputs programmatically in the graphql syntax.

```graphql
input MyInput {
  name: String
}
```
and
```graphql
input MyInput {
  age: Int
}
```
should become
```graphql
input MyInput {
  name: String
  age: Int
}
```
but instead becomes
```graphql
input MyInput {
  name: String
}
input MyInput {
  age: Int
}
```

**Comment by RodMachado** [comment]
Hey @dyst5422,

Thanks to a great discussion with @ccuilla,we don't think that merging similarly named types is the way to go. I can only imagine the confusion it could cause when different devs created similarly named types by mistake and those were simple merged together. Something like:

```
type Address {
  street: String
  city: String
  postalcode: String
}
```
and somewhere else another dev created:
```
type Address {
  street: String
  city: String
  country: String
  zipcode: String
}
```
Now you have `postalcode` and `zipcode`. Another issue would be when a third dev needed to add another attribute, where would he add it? 

With that being said, I strongly believe we shouldn't allow the package to automatically merge types, forcing its specification to happen in only one place.

One good idea that came up while talking about your issue is that we should make the package throw an error if it finds a type specified multiple times. This would prevent accidental duplications.

If you still believe there are reasons where types should be merged, please let me know them so we can discuss about this further.

Cheers!

**Comment by RodMachado** [comment]
Closing this one for now. @dyst5422, feel free to reopen it!

Thanks!

**Comment by dyst5422** [comment]
I agree with your decision on this one. I happen to have a unique circumstance where it is necessary for me to partially define types in multiple locations. I would also highly recommend that you support extension types via the `extend` keyword.
