### ISSUE TITLE
mergeResolvers() fails when find just one resolver file

### ISSUE THREAD

**Issue by erick2014** [okgrow/merge-graphql-schemas#93]
I'm not sure if this is a bug, but I think is kind of weird the fact that I cant just have one resolver or mergeResolvers() call will fail

![imagen](https://user-images.githubusercontent.com/7244087/31184979-7591b61a-a8f0-11e7-8150-21e3a7ce853c.png)

![imagen](https://user-images.githubusercontent.com/7244087/31185044-a608e2aa-a8f0-11e7-9500-89197f08a29a.png)

**Comment by cfnelson** [comment]
@erick2014 This is currently expected behaviour as we are using [merge.all](https://github.com/KyleAMathews/deepmerge#mergeallarrayofobjects-options) from `deepmerge` which expects an array. Relevant code in our repo is [here](https://github.com/okgrow/merge-graphql-schemas/blob/master/src/merge_resolvers.js#L3). 

Potentially we could change this behaviour if it isn't intuitive. @RodMachado Would it make sense to not fail if someone only has one resolver?
